source 'https://rubygems.org'
gem 'hardwired', :git => "git://github.com/nathanaeljones/hardwired.git", :branch => 'develop'
gem 'doc_collector', git: 'https://github.com/imazen/doc_collector.git'
gem 'rake', "~> 13.0"
gem 'hub'