<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\nuget\NugetPackages.targets" />


  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <PackageId>ImageResizer.Plugins.Licensing</PackageId>
    <AssemblyTitle>Licensing support for ImageResizer</AssemblyTitle>
    <Description>Fast image processing and compression backend for the ImageResizer HttpModule.</Description>
    <IsPackable>true</IsPackable>
    <LangVersion>8</LangVersion>
  </PropertyGroup>


  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Imazen.Common">
      <Version>0.9.0-rc02</Version>
    </PackageReference>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageReference Include="System.Memory">
      <Version>4.6.3</Version>
    </PackageReference>
    <PackageReference Include="System.Numerics.Vectors">
      <Version>4.6.1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\ImageResizer.csproj">
      <Name>ImageResizer</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>
