<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <Import Project="..\..\nuget\NugetPackages.targets" />

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Core\ImageResizer.csproj">
      <Name>ImageResizer</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\plugins\ImageResizer.Plugins.Imageflow\ImageResizer.Plugins.Imageflow.csproj">
      <Name>ImageResizer.Plugins.Imageflow</Name>
    </ProjectReference>
  </ItemGroup>
  
  <ItemGroup>
      <PackageReference Include="Imazen.Common" Version="0.9.0-rc01" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
      <PackageReference Include="System.Memory" Version="4.6.3" />
      <PackageReference Include="xunit" Version="2.9.3" />
      <PackageReference Include="xunit.runner.visualstudio" Version="3.1.1">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="coverlet.collector" Version="6.0.4">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
      </PackageReference>

      <PackageReference Include="xunit.should">
          <Version>1.1.0</Version>
      </PackageReference>
  </ItemGroup>

</Project>