<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\nuget\NugetPackages.targets" />


  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <PackageId>ImageResizer.Plugins.Imageflow</PackageId>
    <AssemblyTitle>Imageflow backend for ImageResizer</AssemblyTitle>
    <Description>Fast image processing and compression backend for the ImageResizer HttpModule.</Description>
      <IsPackable>true</IsPackable>
    <PackageReadmeFile>README_IMAGEFLOW.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README_IMAGEFLOW.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Imageflow.Net">
      <Version>0.14.0-rc01</Version>
    </PackageReference>
    <PackageReference Include="Imageflow.NativeRuntime.win-x86">
      <Version>2.1.1-rc10</Version>
    </PackageReference>
    <PackageReference Include="Imageflow.NativeRuntime.win-x86_64">
      <Version>2.1.1-rc10</Version>
    </PackageReference>
    <PackageReference Include="Imazen.Common">
      <Version>0.9.0-rc02</Version>
    </PackageReference>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageReference Include="System.Memory">
      <Version>4.6.3</Version>
    </PackageReference>
    <PackageReference Include="System.Numerics.Vectors">
      <Version>4.6.1</Version>
    </PackageReference>
    <PackageReference Include="System.Text.Json">
      <Version>8.0.5</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\ImageResizer.csproj">
      <Name>ImageResizer</Name>
    </ProjectReference>
    <ProjectReference Include="..\ImageResizer.Plugins.Licensing\ImageResizer.Plugins.Licensing.csproj" />
  </ItemGroup>
</Project>