//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Test.Tools.WicCop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Test.Tools.WicCop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned the value that does not match the mask..
        /// </summary>
        internal static string _0_DontMatchMask {
            get {
                return ResourceManager.GetString("_0_DontMatchMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned duplicated values.
        /// </summary>
        internal static string _0_Duplicated {
            get {
                return ResourceManager.GetString("_0_Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned an empty string..
        /// </summary>
        internal static string _0_EmptyString {
            get {
                return ResourceManager.GetString("_0_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed..
        /// </summary>
        internal static string _0_Failed {
            get {
                return ResourceManager.GetString("_0_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed with incorrect HRESULT..
        /// </summary>
        internal static string _0_FailedWithIncorrectHRESULT {
            get {
                return ResourceManager.GetString("_0_FailedWithIncorrectHRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *{0} file.
        /// </summary>
        internal static string _0_File {
            get {
                return ResourceManager.GetString("_0_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The palette left in the incorrect state after {0}..
        /// </summary>
        internal static string _0_IncorrectStatePalette {
            get {
                return ResourceManager.GetString("_0_IncorrectStatePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned not expected value..
        /// </summary>
        internal static string _0_NotExpectedValue {
            get {
                return ResourceManager.GetString("_0_NotExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned not set value..
        /// </summary>
        internal static string _0_NotSetValue {
            get {
                return ResourceManager.GetString("_0_NotSetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned NULL..
        /// </summary>
        internal static string _0_NULL {
            get {
                return ResourceManager.GetString("_0_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned an item with NULL value..
        /// </summary>
        internal static string _0_NULLItem {
            get {
                return ResourceManager.GetString("_0_NULLItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned a reserved GUID..
        /// </summary>
        internal static string _0_ReservedGUID {
            get {
                return ResourceManager.GetString("_0_ReservedGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} succeded but should fail..
        /// </summary>
        internal static string _0_ShouldFail {
            get {
                return ResourceManager.GetString("_0_ShouldFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value is specified in the field {0}..
        /// </summary>
        internal static string _0_UnexpectedFieldValue {
            get {
                return ResourceManager.GetString("_0_UnexpectedFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned a zero color count pallete..
        /// </summary>
        internal static string _0_ZeroColorPalette {
            get {
                return ResourceManager.GetString("_0_ZeroColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x64.
        /// </summary>
        internal static string Amd64 {
            get {
                return ResourceManager.GetString("Amd64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICBitmapDecoderInfo.
        /// </summary>
        internal static string BitmapDecoderInfoRule_Text {
            get {
                return ResourceManager.GetString("BitmapDecoderInfoRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICBitmapDecoder.
        /// </summary>
        internal static string BitmapDecoderRule_Text {
            get {
                return ResourceManager.GetString("BitmapDecoderRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICBitmapEncoderInfo.
        /// </summary>
        internal static string BitmapEncoderInfoRule_Text {
            get {
                return ResourceManager.GetString("BitmapEncoderInfoRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICBitmapEncoder.
        /// </summary>
        internal static string BitmapEncoderRule_Text {
            get {
                return ResourceManager.GetString("BitmapEncoderRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICBitmapFrameEncode.
        /// </summary>
        internal static string BitmapFrameEncode_Text {
            get {
                return ResourceManager.GetString("BitmapFrameEncode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICBitmapSourceTransform.
        /// </summary>
        internal static string BitmapSourceTransformRule_Text {
            get {
                return ResourceManager.GetString("BitmapSourceTransformRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both ThreadingModel is not supported..
        /// </summary>
        internal static string BothTreadingModelNotSupported {
            get {
                return ResourceManager.GetString("BothTreadingModelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon cannot be extracted..
        /// </summary>
        internal static string CannotExtractIcon {
            get {
                return ResourceManager.GetString("CannotExtractIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed supported pixel format..
        /// </summary>
        internal static string ChangedSupportedPixelFormat {
            get {
                return ResourceManager.GetString("ChangedSupportedPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSID.
        /// </summary>
        internal static string CLSID {
            get {
                return ResourceManager.GetString("CLSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component is disabled..
        /// </summary>
        internal static string ComponentDisabled {
            get {
                return ResourceManager.GetString("ComponentDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM registration is missing..
        /// </summary>
        internal static string ComRegistrationMissing {
            get {
                return ResourceManager.GetString("ComRegistrationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM.
        /// </summary>
        internal static string ComRule_Text {
            get {
                return ResourceManager.GetString("ComRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Formats reported thru IWICBitmapDecoderInfo and IWICBitmapDecoder don&apos;t match..
        /// </summary>
        internal static string ContainerFormatsDoNotMatch {
            get {
                return ResourceManager.GetString("ContainerFormatsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decoder can support animation only if it supports multiframe..
        /// </summary>
        internal static string DecoderAnimationIfMultiframe {
            get {
                return ResourceManager.GetString("DecoderAnimationIfMultiframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decoder does not support multiframe but the file has several frames..
        /// </summary>
        internal static string DecoderDoesNotMultiframe {
            get {
                return ResourceManager.GetString("DecoderDoesNotMultiframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoders.
        /// </summary>
        internal static string Decoders_Text {
            get {
                return ResourceManager.GetString("Decoders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decoder does not support the pixel format but the file has a frame in the pixel format..
        /// </summary>
        internal static string DecoderUnsuportedPixelFormat {
            get {
                return ResourceManager.GetString("DecoderUnsuportedPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICDevelopRaw::QueryRawCapabilitiesInfo(...) reported no supported features..
        /// </summary>
        internal static string DevelopRaw_NoSupportedFeatures {
            get {
                return ResourceManager.GetString("DevelopRaw_NoSupportedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICDevelopRawNotificationCallback::Notify(...) was not called upon the value set..
        /// </summary>
        internal static string DevelopRawRule_NoNotification {
            get {
                return ResourceManager.GetString("DevelopRawRule_NoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICDevelopRawNotificationCallback::Notify(...) was called on the different instance upon the value set..
        /// </summary>
        internal static string DevelopRawRule_NotificationOnWrong {
            get {
                return ResourceManager.GetString("DevelopRawRule_NotificationOnWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICDevelopRaw.
        /// </summary>
        internal static string DevelopRawRule_Text {
            get {
                return ResourceManager.GetString("DevelopRawRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not change the unsupported pixel format..
        /// </summary>
        internal static string DidNotChangeUnsupportedPixelFormat {
            get {
                return ResourceManager.GetString("DidNotChangeUnsupportedPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Channel Masks found..
        /// </summary>
        internal static string DuplicatedChannelMask {
            get {
                return ResourceManager.GetString("DuplicatedChannelMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated Pixel Formats are specified..
        /// </summary>
        internal static string DuplicatedPixelFormat {
            get {
                return ResourceManager.GetString("DuplicatedPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty registry value..
        /// </summary>
        internal static string EmptyRegistryValue {
            get {
                return ResourceManager.GetString("EmptyRegistryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoders.
        /// </summary>
        internal static string Encoders_Text {
            get {
                return ResourceManager.GetString("Encoders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        internal static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        internal static string FileExtennsion {
            get {
                return ResourceManager.GetString("FileExtennsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file with no frames found..
        /// </summary>
        internal static string FileNoFrames {
            get {
                return ResourceManager.GetString("FileNoFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICFormatConverterInfo.
        /// </summary>
        internal static string FormatConverterInfoRule_Text {
            get {
                return ResourceManager.GetString("FormatConverterInfoRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Count.
        /// </summary>
        internal static string FrameCount {
            get {
                return ResourceManager.GetString("FrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Index.
        /// </summary>
        internal static string FrameIndex {
            get {
                return ResourceManager.GetString("FrameIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not support conversion from a cannonical Pixel Format..
        /// </summary>
        internal static string FromCannonicalNotSupported {
            get {
                return ResourceManager.GetString("FromCannonicalNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance of {0} returned by {1} does not match to the instace returned by IWICImagingFactory::GetComponnetInfo(...)..
        /// </summary>
        internal static string InconsistentComponentInfo {
            get {
                return ResourceManager.GetString("InconsistentComponentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent registry value..
        /// </summary>
        internal static string InconsistentRegistryValue {
            get {
                return ResourceManager.GetString("InconsistentRegistryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent registry value type..
        /// </summary>
        internal static string InconsistentRegistryValueType {
            get {
                return ResourceManager.GetString("InconsistentRegistryValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Mask is incorrect..
        /// </summary>
        internal static string IncorrectChannelMask {
            get {
                return ResourceManager.GetString("IncorrectChannelMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect decoder is picked up..
        /// </summary>
        internal static string IncorrectDecoderPickedUp {
            get {
                return ResourceManager.GetString("IncorrectDecoderPickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Length is incorrect..
        /// </summary>
        internal static string IncorrectMaskLegth {
            get {
                return ResourceManager.GetString("IncorrectMaskLegth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry value should a GUID..
        /// </summary>
        internal static string InvalidGUIDRegistryValue {
            get {
                return ResourceManager.GetString("InvalidGUIDRegistryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICBitmapSourceTransform::GetClosestPixelFormat(...) should not change the pixel format if the pixel format of the frame is passed..
        /// </summary>
        internal static string IWICBitmapSourceTransform_ChangedPixelformat {
            get {
                return ResourceManager.GetString("IWICBitmapSourceTransform_ChangedPixelformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICBitmapSourceTransform::GetClosestSize(...) should not change the width and the height if the size of the frame is passed..
        /// </summary>
        internal static string IWICBitmapSourceTransform_ChangedSize {
            get {
                return ResourceManager.GetString("IWICBitmapSourceTransform_ChangedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        internal static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry key is missing..
        /// </summary>
        internal static string MissingRegistryKey {
            get {
                return ResourceManager.GetString("MissingRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry value is missing..
        /// </summary>
        internal static string MissingRegistryValue {
            get {
                return ResourceManager.GetString("MissingRegistryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported or/and no files that expose {0} are provided..
        /// </summary>
        internal static string NoFilesFor_0 {
            get {
                return ResourceManager.GetString("NoFilesFor_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not-registered Pixel Formats are specified..
        /// </summary>
        internal static string NonRegisteredPixelFormat {
            get {
                return ResourceManager.GetString("NonRegisteredPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumericPresentation is not specified..
        /// </summary>
        internal static string NoNumericRepresention {
            get {
                return ResourceManager.GetString("NoNumericRepresention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pixel Formats are specified..
        /// </summary>
        internal static string NoPixelFormats {
            get {
                return ResourceManager.GetString("NoPixelFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurance {0}.
        /// </summary>
        internal static string Occurance {
            get {
                return ResourceManager.GetString("Occurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file pattern does not match but {0} passed..
        /// </summary>
        internal static string PatternDoesnotMatchButPassed {
            get {
                return ResourceManager.GetString("PatternDoesnotMatchButPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated patterns are specified..
        /// </summary>
        internal static string PatternDuplicated {
            get {
                return ResourceManager.GetString("PatternDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Index.
        /// </summary>
        internal static string PatternIndex {
            get {
                return ResourceManager.GetString("PatternIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Indices.
        /// </summary>
        internal static string PatternIndices {
            get {
                return ResourceManager.GetString("PatternIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patterns are specified..
        /// </summary>
        internal static string PatternNo {
            get {
                return ResourceManager.GetString("PatternNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero length pattern is specified..
        /// </summary>
        internal static string PatternZeroLength {
            get {
                return ResourceManager.GetString("PatternZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Photo Gallery Integration.
        /// </summary>
        internal static string PhotoGalleryIntegrationRule_Text {
            get {
                return ResourceManager.GetString("PhotoGalleryIntegrationRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Format.
        /// </summary>
        internal static string PixelFormat {
            get {
                return ResourceManager.GetString("PixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pixel Format Converter is no createable..
        /// </summary>
        internal static string PixelFormatConverterNotCreatable {
            get {
                return ResourceManager.GetString("PixelFormatConverterNotCreatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Format Converters.
        /// </summary>
        internal static string PixelFormatConverters_Text {
            get {
                return ResourceManager.GetString("PixelFormatConverters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWICPixelFormatInfo.
        /// </summary>
        internal static string PixelFormatInfoRule_Text {
            get {
                return ResourceManager.GetString("PixelFormatInfoRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Formats.
        /// </summary>
        internal static string PixelFormats_Text {
            get {
                return ResourceManager.GetString("PixelFormats_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property Store Handler is not creatable..
        /// </summary>
        internal static string PropertyStoreHandlerNotCreatable {
            get {
                return ResourceManager.GetString("PropertyStoreHandlerNotCreatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Property Store Integration.
        /// </summary>
        internal static string PropertyStoreIntegrationRule_Text {
            get {
                return ResourceManager.GetString("PropertyStoreIntegrationRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default).
        /// </summary>
        internal static string RegistryValue_default {
            get {
                return ResourceManager.GetString("RegistryValue_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {0}....
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Explorer Integration.
        /// </summary>
        internal static string ShellIntegrationRule_Text {
            get {
                return ResourceManager.GetString("ShellIntegrationRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Shell Integration.
        /// </summary>
        internal static string ShellIntegrationRuleGroup_Text {
            get {
                return ResourceManager.GetString("ShellIntegrationRuleGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Pixel Formats.
        /// </summary>
        internal static string SupportedPixelFormats {
            get {
                return ResourceManager.GetString("SupportedPixelFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumnail Cache Integration.
        /// </summary>
        internal static string ThumnailCacheIntegrationRule_Text {
            get {
                return ResourceManager.GetString("ThumnailCacheIntegrationRule_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not support conversion to a cannonical Pixel Format..
        /// </summary>
        internal static string ToCannonicalNotSupported {
            get {
                return ResourceManager.GetString("ToCannonicalNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected registry value..
        /// </summary>
        internal static string UnexpectedRegistryValue {
            get {
                return ResourceManager.GetString("UnexpectedRegistryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected registry value type..
        /// </summary>
        internal static string UnexpectedRegistryValueType {
            get {
                return ResourceManager.GetString("UnexpectedRegistryValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon WICCop {
            get {
                object obj = ResourceManager.GetObject("WICCop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOW.
        /// </summary>
        internal static string Wow {
            get {
                return ResourceManager.GetString("Wow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow Key.
        /// </summary>
        internal static string WowKey {
            get {
                return ResourceManager.GetString("WowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented in WOW..
        /// </summary>
        internal static string WowNotImplemented {
            get {
                return ResourceManager.GetString("WowNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x86.
        /// </summary>
        internal static string X86 {
            get {
                return ResourceManager.GetString("X86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits per pixel is zero..
        /// </summary>
        internal static string ZeroBPP {
            get {
                return ResourceManager.GetString("ZeroBPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Count is zero..
        /// </summary>
        internal static string ZeroChannelCount {
            get {
                return ResourceManager.GetString("ZeroChannelCount", resourceCulture);
            }
        }
    }
}
